# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
modelVersion: "1.0"
pipelineId: "pipeline-dataproc-create-batch"
description: "A pipeline with a DataprocCreateBatch task."
runner: "airflow"
owner: "data-eng-team"
tags: ["dataproc_create_batch", "example"]

defaults:
  projectId: "your-gcp-project-id"
  location: "us-central1"
  executionConfig:
    retries: 0

triggers:
  - schedule:
      interval: "0 5 * * *"
      startTime: "2025-10-01T00:00:00"
      endTime: "2026-10-01T00:00:00"
      catchup: false
      timezone: "UTC"

actions:
  - notebook:
      name: "run-notebook-on-dataproc-serverless"
      mainFilePath: "./data/notebookWithArchivesCheck.ipynb"
      params:
        execution_date: "2026-01-01"
      archiveUris:
        - "./data/custom_venv.tar.gz"
      stagingBucket: "your-bucket"
      engine:
        dataprocServerless:
          location: "us-central1"
          resourceProfile:
            inline:
              environmentConfig:
                executionConfig:
                  serviceAccount: "your-service-account@your-gcp-project-id.iam.gserviceaccount.com"
                  subnetworkUri: "projects/your-gcp-project-id/regions/us-central1/subnetworks/default"
              runtimeConfig:
                version: "2.3"
                properties:
                  spark.app.name: "run-notebook-on-dataproc-serverless"
                  spark.executor.instances: "2"
                  spark.driver.cores: "4"
                  spark.dataproc.driverEnv.PYTHONPATH: "./libs/lib/python3.11/site-packages"
                  spark.executorEnv.PYTHONPATH: "./libs/lib/python3.11/site-packages"
